import React, { useState } from "react";
import Head from "next/head";
import * as style from "./style";

function Search() {
  const [search, setSearch] = useState("");
  const [listReceive, setListReceive] = useState([]);
  const handleSearchData = async () => {
    if (search !== "") {
      const result = await fetch(
        `http://localhost:3000/api/search?query=${search}`
      );
      const json = await result.json();
      setListReceive(json.list);
    } else {
      console.log("algo falhou");
    }
  };

  return (
    <style.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style.Header>
        <a>trending</a>
        <a href="localhost:3000">search</a>
      </style.Header>
      <input
        type="text"
        placeholder="digite o nome do filme"
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />
      <button onClick={handleSearchData}>buscar</button>
      <ul>
        {listReceive.map((item) => (
          <li key={item.id}>
            {item.title} <br />
            <img
              src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
              width="390"
            />
          </li>
        ))}
      </ul>
    </style.Container>
  );
}

export default Search;
