import React, { useState } from "react";
import Head from "next/head";
import * as style from "./style";

function Search() {
  const [search, setSearch] = useState("");
  const handleSearchData = async () => {
    if (search !== "") {
      const res = await fetch(`http://localhost:3000/api/search?q=${search}`);
      const json = await res.json();
      console.log(json.backdrop_path);
    } else {
      console.log("algo falhou");
    }
  };

  return (
    <style.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style.Title>Busque o filme desejado</style.Title>
      <input
        type="text"
        placeholder="digite o nome do filme"
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />
      <h2>{search}</h2>
      <button onClick={handleSearchData}>buscar</button>
    </style.Container>
  );
}

export default Search;
