import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ name }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>top trends</h1>
      <h2>ola {name}</h2>
    </div>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      name: "guizin",
    },
  };
}
