import Head from "next/head";
import * as style from "../styles/home.style";
import styles from "../styles/Home.module.css";

export default function Home({ list }) {
  return (
    <style.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>trending movies</h1>
      <ul id="onorderList">
        {list.map((item) => (
          <li id="movieList">
            {item.title} <br />
            <img
              src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
              width="150"
            />
          </li>
        ))}
      </ul>
    </style.Container>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/trending");
  const json = await res.json();
  return {
    props: {
      list: json.list,
    },
  };
}
